<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Fluentio</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Fluentio_files/libs/clipboard/clipboard.min.js"></script>
<script src="Fluentio_files/libs/quarto-html/quarto.js"></script>
<script src="Fluentio_files/libs/quarto-html/popper.min.js"></script>
<script src="Fluentio_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Fluentio_files/libs/quarto-html/anchor.min.js"></script>
<link href="Fluentio_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Fluentio_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Fluentio_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Fluentio_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Fluentio_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contents</h2>
   
  <ul>
  <li><a href="#question-1" id="toc-question-1" class="nav-link active" data-scroll-target="#question-1">Question 1</a></li>
  <li><a href="#question-2" id="toc-question-2" class="nav-link" data-scroll-target="#question-2">Question 2</a></li>
  <li><a href="#question-3" id="toc-question-3" class="nav-link" data-scroll-target="#question-3">Question 3</a></li>
  <li><a href="#question-4" id="toc-question-4" class="nav-link" data-scroll-target="#question-4">Question 4</a></li>
  <li><a href="#question-5" id="toc-question-5" class="nav-link" data-scroll-target="#question-5">Question 5</a></li>
  <li><a href="#question-6" id="toc-question-6" class="nav-link" data-scroll-target="#question-6">Question 6</a></li>
  <li><a href="#question-7" id="toc-question-7" class="nav-link" data-scroll-target="#question-7">Question 7</a>
  <ul class="collapse">
  <li><a href="#background-and-objectives" id="toc-background-and-objectives" class="nav-link" data-scroll-target="#background-and-objectives">1. Background and objectives</a></li>
  <li><a href="#hypothesis" id="toc-hypothesis" class="nav-link" data-scroll-target="#hypothesis">2. Hypothesis</a></li>
  <li><a href="#experimental-design" id="toc-experimental-design" class="nav-link" data-scroll-target="#experimental-design">3. Experimental Design</a></li>
  <li><a href="#possible-threats-to-validity" id="toc-possible-threats-to-validity" class="nav-link" data-scroll-target="#possible-threats-to-validity">4. Possible threats to validity</a></li>
  <li><a href="#analysis-plan" id="toc-analysis-plan" class="nav-link" data-scroll-target="#analysis-plan">5. Analysis plan</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Fluentio</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="question-1" class="level1">
<h1>Question 1</h1>
<p>Use the historical data to calculate ARPU and SDRPU</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># import library</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpact)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># import data</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">'https://raw.githubusercontent.com/jefftwebb/data/main/fluent_historical.csv'</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 6
  customer_id plan  date       month  paid type    
  &lt;chr&gt;       &lt;chr&gt; &lt;date&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;   
1 AK59729     free  2024-01-01     1 30.2  purchase
2 DE52995     free  2024-01-01     1 28.9  purchase
3 ED41801     free  2024-01-01     1  7.65 purchase
4 EZ25368     free  2024-01-01     1  4.9  purchase
5 HM45834     free  2024-01-01     1 10.2  purchase
6 JB35173     free  2024-01-01     1 29.6  purchase</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate arpu and sdrpu</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(customer_id, month) <span class="sc">%&gt;%</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">monthly_revenue =</span> <span class="fu">sum</span>(paid), <span class="at">.groups =</span> <span class="st">'drop'</span>) <span class="sc">%&gt;%</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">arpu =</span> <span class="fu">mean</span>(monthly_revenue),</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">sdrpu =</span> <span class="fu">sd</span>(monthly_revenue))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
   arpu sdrpu
  &lt;dbl&gt; &lt;dbl&gt;
1  2.83  10.9</code></pre>
</div>
</div>
<p>ARPU = 2.82 SDRPU = 10.94</p>
</section>
<section id="question-2" class="level1">
<h1>Question 2</h1>
<p>What is the total sample size required for a traditional fixed duration A/B test, assuming ARPU of 3.00, MEI of .50 and SDRPU of $11.00?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">power.t.test</span>(<span class="at">delta =</span> <span class="fl">0.5</span>,</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">sd =</span> <span class="dv">11</span>,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">sig.level =</span> <span class="fl">0.05</span>,</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">power =</span> .<span class="dv">8</span>,</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">alternative =</span> <span class="st">"one.sided"</span>)<span class="sc">$</span>n</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>total_sample_size <span class="ot">&lt;-</span> <span class="fu">ceiling</span>(n) <span class="sc">*</span> <span class="dv">2</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>total_sample_size</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11972</code></pre>
</div>
</div>
<p>Each group needs 5956 samples. Total sample size is 11972.</p>
</section>
<section id="question-3" class="level1">
<h1>Question 3</h1>
<p>What is the required duration in days for this A/B test using the sample size from the previous question? Hint: Calculate the average number of new subscribers (free or paid) per day in 2024. This count should exclude customers making repeat subscription payments, using only their first appearance in the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>avg_new_mem <span class="ot">&lt;-</span> df <span class="sc">|&gt;</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(customer_id, date) <span class="sc">|&gt;</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(customer_id)<span class="sc">|&gt;</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span>) <span class="sc">|&gt;</span>  </span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(date) <span class="sc">|&gt;</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">n =</span> <span class="fu">n</span>(), <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">|&gt;</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">avg_new_mem =</span> <span class="fu">mean</span>(n)) <span class="sc">|&gt;</span> </span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(avg_new_mem)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>avg_new_mem</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 85.65774</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>duration <span class="ot">&lt;-</span> total_sample_size<span class="sc">/</span>avg_new_mem</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>duration</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 139.7655</code></pre>
</div>
</div>
<p>Required duration is 140 days or approximately 4.6 months.</p>
</section>
<section id="question-4" class="level1">
<h1>Question 4</h1>
<p>We can definitely use CUPED in this project because monthly data is available and there are new users every day. We can use the previous month revenue (for example January) and the subsequent month revenue to calculate the correlation and subsequently, the required sample size and duration. Having these in minds, we can set up an experiment accordingly.</p>
</section>
<section id="question-5" class="level1">
<h1>Question 5</h1>
<p>Size this experiment for a group sequential test with 4 checkpoints. The parameters will be the same: ARPU of 3.00, MEI of .50 and SDRPU of 11.00. Alpha and beta spending will be defined with O’Brien-Fleming. You keep alpha at .05 and power at .8.</p>
<ul>
<li>What are the sample sizes at each checkpoint?</li>
<li>What is the expected sample size under H1?</li>
<li>What would the duration of the experiment be given the expected sample size under H1?</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># size the experiment for a group sequential test with 4 checkpoints.</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">getDesignGroupSequential</span>(<span class="at">typeOfDesign =</span> <span class="st">"asOF"</span>, <span class="at">kMax =</span> <span class="dv">5</span>,</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">alpha =</span> <span class="fl">0.05</span>, <span class="at">beta =</span> .<span class="dv">2</span>, <span class="at">typeBetaSpending =</span> <span class="st">"bsOF"</span>) <span class="sc">|&gt;</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">getSampleSizeMeans</span>(<span class="at">alternative =</span> <span class="fl">0.5</span>, <span class="at">stDev =</span> <span class="dv">11</span>) <span class="sc">|&gt;</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summary</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><em>Sample size calculation for a continuous endpoint</em></p>
<p>Sequential analysis with a maximum of 5 looks (group sequential design), one-sided overall significance level 5%, power 80%. The results were calculated for a two-sample t-test, H0: mu(1) - mu(2) = 0, H1: effect = 0.5, standard deviation = 11.</p>
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Stage</th>
<th>1</th>
<th>2</th>
<th>3</th>
<th>4</th>
<th>5</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Planned information rate</td>
<td>20%</td>
<td>40%</td>
<td>60%</td>
<td>80%</td>
<td>100%</td>
</tr>
<tr class="even">
<td>Cumulative alpha spent</td>
<td>&lt;0.0001</td>
<td>0.0019</td>
<td>0.0114</td>
<td>0.0284</td>
<td>0.0500</td>
</tr>
<tr class="odd">
<td>Cumulative beta spent</td>
<td>0.0042</td>
<td>0.0427</td>
<td>0.0980</td>
<td>0.1519</td>
<td>0.2000</td>
</tr>
<tr class="even">
<td>Stage levels (one-sided)</td>
<td>&lt;0.0001</td>
<td>0.0019</td>
<td>0.0108</td>
<td>0.0249</td>
<td>0.0410</td>
</tr>
<tr class="odd">
<td>Efficacy boundary (z-value scale)</td>
<td>4.229</td>
<td>2.888</td>
<td>2.298</td>
<td>1.962</td>
<td>1.740</td>
</tr>
<tr class="even">
<td>Futility boundary (z-value scale)</td>
<td>-1.432</td>
<td>-0.028</td>
<td>0.720</td>
<td>1.248</td>
<td></td>
</tr>
<tr class="odd">
<td>Efficacy boundary (t)</td>
<td>1.755</td>
<td>0.847</td>
<td>0.550</td>
<td>0.407</td>
<td>0.322</td>
</tr>
<tr class="even">
<td>Futility boundary (t)</td>
<td>-0.594</td>
<td>-0.008</td>
<td>0.172</td>
<td>0.259</td>
<td></td>
</tr>
<tr class="odd">
<td>Cumulative power</td>
<td>0.0013</td>
<td>0.1187</td>
<td>0.4218</td>
<td>0.6799</td>
<td>0.8000</td>
</tr>
<tr class="even">
<td>Number of subjects</td>
<td>2818.6</td>
<td>5637.2</td>
<td>8455.8</td>
<td>11274.3</td>
<td>14092.9</td>
</tr>
<tr class="odd">
<td>Expected number of subjects under H1</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>9812.7</td>
</tr>
<tr class="even">
<td>Overall exit probability (under H0)</td>
<td>0.0761</td>
<td>0.4177</td>
<td>0.2947</td>
<td>0.1460</td>
<td></td>
</tr>
<tr class="odd">
<td>Overall exit probability (under H1)</td>
<td>0.0054</td>
<td>0.1560</td>
<td>0.3584</td>
<td>0.3120</td>
<td></td>
</tr>
<tr class="even">
<td>Exit probability for efficacy (under H0)</td>
<td>&lt;0.0001</td>
<td>0.0019</td>
<td>0.0095</td>
<td>0.0166</td>
<td></td>
</tr>
<tr class="odd">
<td>Exit probability for efficacy (under H1)</td>
<td>0.0013</td>
<td>0.1175</td>
<td>0.3031</td>
<td>0.2581</td>
<td></td>
</tr>
<tr class="even">
<td>Exit probability for futility (under H0)</td>
<td>0.0761</td>
<td>0.4158</td>
<td>0.2853</td>
<td>0.1294</td>
<td></td>
</tr>
<tr class="odd">
<td>Exit probability for futility (under H1)</td>
<td>0.0042</td>
<td>0.0386</td>
<td>0.0553</td>
<td>0.0539</td>
<td></td>
</tr>
</tbody>
</table>
<p>Legend:</p>
<ul>
<li><em>(t)</em>: treatment effect scale</li>
</ul>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>gst_duration <span class="ot">&lt;-</span> <span class="dv">9814</span><span class="sc">/</span>avg_new_mem</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>gst_duration</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 114.5723</code></pre>
</div>
</div>
<ul>
<li>The sample size is 2820, 5638, 8456, 11276 at each checkpoint.</li>
<li>The expected sample size under H1 is 9814</li>
<li>The duration given expected sample size at H1 is 115 days</li>
</ul>
</section>
<section id="question-6" class="level1">
<h1>Question 6</h1>
<p>Suppose that the true effect of the treatment is $.25. What is the probability given this group sequential design that the experiment could be stopped early?</p>
<p>If true effect of the treatment is 0.25, it is less than MEI of 0.5 (H0). It is likely that we would stop the experiment early as we discover this effect at an early checkpoint. The probability for early stopping under H0 is 0.0761, 0.4177, 0.2947, 0.1460 from checkpoint 1 to 4 respectively. It looks like we are most likely to be able to reject H1 at checkpoint 2 as it has the highest probability of 0.42. Interestingly, the expected sample size if H1 is true is 9814, while it is 8456 and 11276 at checkpoint 3 and 4 respectively. This means if we don’t stop at checkpoint 2, we will still be able to stop somewhere between checkpoint 3 and 4 where there is enough sample size for H1.</p>
</section>
<section id="question-7" class="level1">
<h1>Question 7</h1>
<p>Write a brief proposal for the experiment based on your research that includes discussion of:</p>
<section id="background-and-objectives" class="level2">
<h2 class="anchored" data-anchor-id="background-and-objectives">1. Background and objectives</h2>
<p>Our team is always striving for increase revenue through optimizing the pricing structure of the sucscription plans. In our current “freemium” subscription model, we have 2 plans: Free and Plus (USD 9.99). We want to consider adding one more Pro plan (USD 14.99) with more advanced features and conduct an A/B Test to decide whether it impacts our average revenue per user (ARPU).</p>
<p>Following is the details on each plan:</p>
<ul>
<li>Free plan: Ad-supported with limited features</li>
<li>Plus plan: $9.99/month with ad-free experience</li>
<li>Pro plan: $14.99/month with ad-free experience, pronunciation training and simulated conversation with AI, and advanced calendaring tools with reminders to maintain progress</li>
</ul>
</section>
<section id="hypothesis" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis">2. Hypothesis</h2>
<ul>
<li>H0: The ARPU difference between the treatment and control group is less than or equal to the minimal effect of interest of $0.5</li>
<li>H1: The ARPU difference between the treatment and control group is greater than the minimal effect of interest of $0.5</li>
</ul>
</section>
<section id="experimental-design" class="level2">
<h2 class="anchored" data-anchor-id="experimental-design">3. Experimental Design</h2>
<p>We will conduct group sequential test with 4 checkpoints. The point of using this method is to allow for early experiment stopping in case of either insignificant or significant effect. In particular, we will apply O’Brien-Fleming to allow for early conservative experiment, reducing the risk of mistakenly concluding there is an effect while there is actually not early on. Users will be randomly assigned to either the control group (existing design with free and plus plan) or the treatment group (new design with free, plus and pro plan) to ensure unbiased comparisons.</p>
<ul>
<li>Success metrics: ARPU increases by USD 0.5</li>
<li>Minimum Effect of Interest (MEI) = 0.5</li>
<li>alpha = 0.05</li>
<li>beta = 0.2</li>
<li>sample size = 2820, 5638, 8456, 11276 at each checkpoint</li>
<li>test duration = 115 days or 3 months and 23 days</li>
</ul>
</section>
<section id="possible-threats-to-validity" class="level2">
<h2 class="anchored" data-anchor-id="possible-threats-to-validity">4. Possible threats to validity</h2>
<p>There are some popular threats that could affect experiment validity:</p>
<ul>
<li>Selection bias: the sample is not representative of your entire audience. For example, in order to manipulate the result, the team runs experiment with the population that is most likely to sign up for Pro plan.</li>
<li>Instrumentation effect: errors related to your testing tool and code implementations. For example, during the test, there are IT issues leading to a portion of users in treatment group not able to log in.</li>
<li>The company runs a promotion only to a subset of users that disproportionately overlaps with the control group. This could increase ARPU in control, making the Pro plan look less effective than it really is.</li>
<li>A competitor launches a new language app with a huge discount during the test. If users in the treatment group are more likely to be affected, ARPU could drop in the treatment group independently of the new pricing structure</li>
</ul>
</section>
<section id="analysis-plan" class="level2">
<h2 class="anchored" data-anchor-id="analysis-plan">5. Analysis plan</h2>
<ul>
<li>Step 1: Communicate the plan with the internal team and stakeholders (engineer, product team) to set up the experiment</li>
<li>Step 2: Run group sequential test A/B testing for the whole period (no change on the experimental design). During the testing period, track the arpu to ensure the number is correct (i.e if there is a sudden increase/decrease in the number)</li>
<li>Step 3: At each checkpoint, calculate arpu for each group and run a t-test to ensure statistical significance. We can stop at efficacy or futility if necessary</li>
<li>Step 4: Discuss the result with stakeholders and decide next step</li>
<li>Note: Regardless of failed or successful test, document all insights and learning lessons for future reference</li>
</ul>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>